### ISSUE TITLE
New requirments for Android

### ISSUE THREAD

**Issue by albert-pixel** [the16bitgamer/Unity_Android_iOS_App_Detection#2]
First of all, thanks for this plugin! It works :D
I just want to add that for new Android versions it's mandatory to "Declare package visibility needs". See documentation here:

https://developer.android.com/training/package-visibility/declaring

To recap: It's mandatory to declare, in the Android Manifest, what packages you want to interact with.

Thanks!

**Comment by the16bitgamer** [comment]
Thank you for letting me know. Unfortunately due to to the recent changes in Unity's Privacy Police we are moving away from the Unity Engine.

As such we have made public the Android Studio Project we used to create the native android plugin here: https://github.com/the16bitgamer/NetworkCheck

I will also do one last test. From the looks of thing one could simply add the manifest into the android plugin folder and add the string there. If so I will update the project and add in new instructions.

However after this I will most likely archive this repository as we will no longer be doing development or business with unity.

**Comment by the16bitgamer** [comment]
At this point we cannot update the Unity Packages. I attempted to add a manifest into Unity however it didn't work. The current work around is to rebuild the appcheck.aar from our NetworkCheck repository, as the check is done by our plugin not the Unity application.

Due to the new privacy concerns provided one could request the "QUERY_ALL_PACKAGES" permission, however this will ultimatly get the app rejected.

One could theoretically duplicate how we check for our apps in iOS by having a new Plugin respond to a specific URL request, and have our application detect if an application like it is installed. However this is out of scope for this project, and most likely out of scope for most users, as it will require a dedicated plugin to respond, since it cannot be generated like you can in iOS.

I will now be closing this issue, as we do not intend on fixing this issue.
